use_frameworks!

target 'MyProjectModule' do
  pod 'Masonry'
  pod 'YYKit'
  pod 'pop', '~> 1.0'
  pod 'MJExtension'
  pod 'AFNetworking'
  pod 'KVOController'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'YTKNetwork'

end
