use_frameworks!

target 'MyProjectModule' do
  pod 'Masonry'
  pod 'YYKit'
  pod 'pop', '~> 1.0'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'KVOController'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'YTKNetwork'
  pod 'Aspects'

  # Flutter 引入 现有 Native 工程
  flutter_application_path = "/Users/zhangxinxin/Code/AndroidStudioProjects/flutter_module"
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

end
